# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "[Action Push] Build and Tests | Auto Pull Request" #CI/CD Pipeline - C# (.NET) | Auto Pull Request

on:
  push:
    branches-ignore:
      - main   # ignora pushes na main, s칩 roda nas outras branches

permissions:
  contents: write
  pull-requests: write   

jobs:
  # 1. Build e Testes
  build-and-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout c칩digo
      uses: actions/checkout@v4
      
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restaurar depend칡ncias
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Rodar Testes
      run: dotnet test --configuration Release --no-build --verbosity normal
      
  # 2. Criar ou atualizar Pull Request
  create-pr:
    needs: build-and-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # importante para push do PR
          fetch-depth: 0   # importante para detectar mudan칞as

      - name: Autenticar CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Criar Pull Request autom치tico
        run: |
          gh pr create \
            --base main \
            --head "${{ github.ref_name }}" \
            --title "PR criada automaticamente para main - ${{ github.ref_name }}" \
            --body "游 Pull request autom치tico criado a partir do push em `${{ github.ref_name }}`."
